[lab]
jetson   ansible_host=${JETSON_IP}  ansible_user=nvidia
rpi2     ansible_host=${RPI2_IP} ansible_user=pi
recamera ansible_host=${RECAMERA_IP} ansible_user=root

[openwrt]
beryl    ansible_host=${BERYL_IP} ansible_user=root

[lab:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o IdentitiesOnly=yes'

[openwrt:vars]
ansible_python_interpreter=/dev/null
ansible_shell_type=sh
