---
- name: Install and configure prometheus-node-exporter
  hosts: lab,!recamera
  become: yes
  tasks:
    - name: Install node-exporter
      apt:
        name: prometheus-node-exporter
        state: present
        update_cache: yes

    - name: Enable and start node-exporter
      systemd:
        name: prometheus-node-exporter
        enabled: yes
        state: started
