---
- name: Configure systemd-timesyncd
  hosts: lab, !recamera
  become: yes
  tasks:
    - name: Ensure systemd-timesyncd is installed
      apt:
        name: systemd-timesyncd
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure NTP servers
      copy:
        dest: /etc/systemd/timesyncd.conf
        content: |
          [Time]
          NTP=pool.ntp.org
          FallbackNTP=time.cloudflare.com
      notify: restart timesyncd

    - name: Enable and start timesyncd
      systemd:
        name: systemd-timesyncd
        enabled: yes
        state: started
    - name: Set timezone
      community.general.timezone:
        name: America/Los_Angeles

  handlers:
    - name: restart timesyncd
      systemd:
        name: systemd-timesyncd
        state: restarted
